### ISSUE TITLE
远程服务器授权失败2

### ISSUE THREAD

**Issue by WilliamL71Oi** [uknowsec/Fofa-gui#2]
搜索去到10%就提示：远程服务器授权失败。
然后闪退。

多次参尝试依然如此。

**Comment by uknowsec** [comment]
普通会员API查询数据免费前100条/次，充钱你可以变得更强！

**Comment by WilliamL71Oi** [comment]
> 
> 
> 普通会员API查询数据免费前100条/次，充钱你可以变得更强！

但这个软件也不能报错+闪退吧。
