### ISSUE TITLE
程序不稳定啊

### ISSUE THREAD

**Issue by xibeiwangxue** [uknowsec/Fofa-gui#4]
扫描的时候速度是很快，但是每次扫到一半就自动退出，都没有正常结束过

**Comment by NittaAkio** [comment]
同上，10%弹出502或者504错误。每次都是一样，只能采集到100条

**Comment by uknowsec** [comment]
> 同上，10%弹出502或者504错误。每次都是一样，只能采集到100条

程序是通过fofa api实现查询的，fofa api，普通会员只支持查询条100条。
