### ISSUE TITLE
远程服务器反回错误:(401)

### ISSUE THREAD

**Issue by kokxxoo** [uknowsec/Fofa-gui#5]
远程服务器反回错误:(401)，未将对象引用设置到对象的实例
邮箱和key都设置正确

**Comment by 2533537399** [comment]
求解决啊，我也是这个错误，请问楼上问题解决了吗

**Comment by uknowsec** [comment]
> 求解决啊，我也是这个错误，请问楼上问题解决了吗

先确定fofa.so是否通，然后确定key是否填写正确。

**Comment by 2533537399** [comment]
好嘞楼主现在好用了&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Uknow"<notifications@github.com&gt;; 
发送时间: 2020年11月7日(星期六) 中午11:20
收件人: "uknowsec/Fofa-gui"<Fofa-gui@noreply.github.com&gt;; 
抄送: "JIANG"<2533537399@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [uknowsec/Fofa-gui] 远程服务器反回错误:(401) (#5)





  
求解决啊，我也是这个错误，请问楼上问题解决了吗
  
先确定fofa.so是否通，然后确定key是否填写正确。
