### ISSUE TITLE
报错，远程服务器返回错误：（401）未经授权

### ISSUE THREAD

**Issue by littleheary** [uknowsec/Fofa-gui#6]
输入的email和key确定是正确的。重新输入了好几遍。
但是还是运行就提示“远程服务器返回错误：（401）未经授权”

**Comment by uknowsec** [comment]
> 输入的email和key确定是正确的。重新输入了好几遍。
> 但是还是运行就提示“远程服务器返回错误：（401）未经授权”

curl "https://fofa.so/api/v1/info/my?email=${FOFA_EMAIL}&key=${FOFA_KEY}"
试试，如果也报401就是你账号的问题
用的fofa api如果不是会员用不了的。

**Comment by littleheary** [comment]
我擦，原来是需要购买会员的么。尴尬了。

**Comment by mingones** [comment]
我是高级会员，但是在扫描页数过大的时候，还是会报这个错误
